logo: # add logo name
title: Contadores de Estrellas - Proyecto de Ciencia Ciudadana para registrar las lluvias de estrellas
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: contadoresdeestrellas-family.jpg # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: logo-upm.jpg # your photo
author-name: Equipo de contadores # your name
about-author: UPM + IAC # about author
email: proyectocontadoresdeestrellas@gmail.com # your email
phone: (496)-169-6557 # your pnone number
website: http://www.contadoresdeestrellas.github.io/bef # you website


author-pic: logo-iac.jpg # your photo
author-name: Equipo de contadores # your name
about-author: IAC # about author
email: proyectocontadoresdeestrellas@gmail.com # your email
phone: (496)-169-6557 # your pnone number
website: http://www.contadoresdeestrellas.github.io/bef # you website

# Social link
twitter_url:   http://twitter.com/starcounters
instagram_url: https://www.instagram.com/contadoresdeestrellas/
facebook_url:  http://www.facebook.com/contadoresdeestrellas/ 

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
